name: Vercel Preview Deployment

'on':
  push:
    branches: feature/practice-three
  defaults: 
    run:
      working-directory: practices/practice-three

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile
       
      - name: Install Vercel CLI
        run: yarn add --global vercel@latest
